"""Constants for Ambeo Soundbar integration."""

DOMAIN = "ambeo_soundbar"
PLATFORMS = ["binary_sensor", "button", "light", "media_player", "number", "switch"]
VERSION = "1.1.0"
MANUFACTURER = "Sennheiser"
DEFAULT_PORT = 80
TIMEOUT = 5

CONFIG_HOST = "host"
CONFIG_DEBOUNCE_COOLDOWN = "debounce_cooldown"
CONFIG_DEBOUNCE_COOLDOWN_DEFAULT = 0
CONFIG_HOST_DEFAULT = "ambeo.local"
CONFIG_UPDATE_INTERVAL = "update_interval"
CONFIG_UPDATE_INTERVAL_DEFAULT = 10

BRIGHTNESS_SCALE = (0, 100)
DEFAULT_BRIGHTNESS = 50
BRIGHTNESS_SCALE_AMBEO_MAX_DISPLAY = (1, 126)
DEFAULT_BRIGHTNESS_AMBEO_MAX = 128
BRIGHTNESS_SCALE_AMBEO_MAX_LOGO = (1, 118)
