DOMAIN = "ambeo_soundbar"
VERSION = "1.0.0"
DEFAULT_BRIGHTNESS = 50
BRIGHTNESS_SCALE = (0, 100)
BRIGHTNESS_SCALE_AMBEO_MAX_LOGO = (1, 118)
BRIGHTNESS_SCALE_AMBEO_MAX_DISPLAY = (1, 126)
EXCLUDE_SOURCES_MAX = ["aes"]

DEFAULT_BRIGHTNESS_AMBEO_MAX = 128


