homeassistant:
  name: Dev
  unit_system: metric
  time_zone: Europe/Paris

http:

debugpy:
  start: true
  wait: false
  host: "0.0.0.0"
  port: 5678

logger:
  default: warning
  logs:
    custom_components.ambeo_soundbar: debug
